name: CI

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
  push:
    branches: "main"
jobs:
  test:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }} 
        
      - name: Build and run dev container task
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/ruby-ui/web-devcontainer
          cacheFrom: ghcr.io/ruby-ui/web-devcontainer
          push: always
          runCmd: |
            bundle exec standardrb
            bin/rails test:prepare
            bin/rails db:test:prepare
            bin/rails test

  heroku-deploy:
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/PhlexUI-web' }}
    needs: [test]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.14.15
        with:
          branch: PhlexUI-web
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "phlex-ui-web"
          heroku_email: "seth@statecert.com"

  fly-deploy:
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    needs: [test]
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: deploy-group
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
