name: CI

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
  push:
    branches: "main"
jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: ".node-version"
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Lint code for consistent style
        run: bundle exec standardrb
        
      - name: Run tests
        run: |
          bin/rails test:prepare
          bin/rails db:test:prepare
          bin/rails test

  docker-build:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }} 
        
      - name: Build and run dev container task
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/ruby-ui/web-devcontainer
          cacheFrom: ghcr.io/ruby-ui/web-devcontainer
          push: always
        

  next-deploy:
    if: github.ref == 'refs/heads/main'
    needs: [test, docker-build]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Deploy to Heroku Prod
        run: git push https://heroku:${{ secrets.HEROKU_RUBYUI_API_KEY }}@git.heroku.com/rubyui-next.git HEAD:main
