name: CI

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - main
      - v1

jobs:
  scan:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Build and run dev container task
        uses: devcontainers/ci@v0.3
        with:
          runCmd: |
            bundle install
            # Add scan commands here

  lint:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Build and run dev container task
        uses: devcontainers/ci@v0.3
        with:
          runCmd: bundle exec standardrb

  test:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Build and run dev container task
        uses: devcontainers/ci@v0.3
        with:
          runCmd: |
            bin/setup --skip-server
            bin/rails test:prepare
            bin/rails db:test:prepare
            bin/rails test

  heroku-deploy:
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/PhlexUI-web' }}
    needs: [lint, test]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.14
        with:
          branch: PhlexUI-web
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "phlex-ui-web"
          heroku_email: "seth@statecert.com"

  fly-deploy:
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    needs: [lint, test]
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: deploy-group
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
