name: Verify components

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
  push:
    branches: "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build
        run: bin/rails g ruby_ui:component:all --force true

      - uses: CatChen/check-git-status-action@v1
        with:
          fail-if-not-clean: true
          push-if-not-clean: false
          request-changes-if-not-clean: false
          targets: 'app'
