name: Verify components

on:
  push:
    branches: "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: ".node-version"
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: bin/rails g ruby_ui:component:all --force true

      - uses: CatChen/check-git-status-action@v1
        with:
          fail-if-not-clean: true
          push-if-not-clean: false
          request-changes-if-not-clean: false
          targets: 'app'
